### ISSUE TITLE
Nano / CC1101 pins

### ISSUE THREAD

**Issue by buitre-buitaker** [smar000/evohome-Listener#10]
Hi!

I followed your guide, but I can not figure out the pin connection for a Nano.

You have this reference in your project:

WIRE COLOUR	CC1101 PIN 	NANO PIN
Red 				Vcc	                3.3V pin
Black 			GND 		GND
Orange 			MOSI		15
Yellow 			SCLK		17
Blue				MISO		16
Dark Red 		GDO2		32
Grey				GDO0 		1
White 			CSN 		14

ANT 			Antenna coil

Nanos only have 30 pins and you have 32 for GDO2 (for example), what kind of numering are you using?

Thank you!

**Comment by buitre-buitaker** [comment]
OK, physical pins... sorry

**Comment by smar000** [comment]
Hi
I was using something like the following: http://christianto.tjahyadi.com/wp-content/uploads/2014/11/nano.jpg (looking at the numbers in the grey boxes)

**Comment by buitre-buitaker** [comment]
Yes! Those are physical chip pins, it's perfect! Thank you
