### ISSUE TITLE
HCE80 UFH controller 3150 messages differ from HCC80

### ISSUE THREAD

**Issue by TonyMercer** [smar000/evohome-Listener#11]
As discussed at https://www.automatedhome.co.uk/vbulletin/showthread.php?6087-evohome-HCE80-UFH-valve-state-decoding-from-radio-signals&p=41770#post41770
Here's logs from evohome-listener downloaded 26th Jan 2020.
Please consider as low-priority feature request.
Also in the logs are messages from HCW82 03: sensors which I gather are new to the code.
Please let me know if you want more info / correlations with zone state lights, panel temperatures etc.

[events.log](https://github.com/smar000/evohome-Listener/files/4113779/events.log)
[evogateway.log](https://github.com/smar000/evohome-Listener/files/4113783/evogateway.log)

**Comment by smar000** [comment]
Could you try the current version from the repo. This should give a proper stack trace of where the error is actually occuring.

Also looking at everything again, I have a suspicioun that the issue may be due to having 2 HCE80 controllers, both of which have the same ufh zoneId values - something which I had not considered before. To test this, can you remove one of these and see if the error still arises?

Thanks.

**Comment by TonyMercer** [comment]
THanks
Here's logs with 1.9.7, and a screen clip for the print(traceback... from the 02: message parsing

I did wonder about having the 2 HCE80s. It's not so easy to turn one off right now but I could do it next weekend.


[events.log](https://github.com/smar000/evohome-Listener/files/4114608/events.log)
[evogateway.log](https://github.com/smar000/evohome-Listener/files/4114611/evogateway.log)
![ehohome-listner-screenshot](https://user-images.githubusercontent.com/37899815/73142695-c0595a80-4089-11ea-87e0-f692ad4ce694.png)

**Comment by smar000** [comment]
Actually the problem was a much simpler issue - all my zone names had spaces in them (which the code was therefore counting on), and so your zone names 'HCE80_1' and 'HCE80_2' made the code fall over.

I've updated the code, which should hopefully resolve this issue.

**Comment by TonyMercer** [comment]
Good stuff. That's fixed it

**Comment by smar000** [comment]
Good to hear!
