### ISSUE TITLE
controlling TRVs based on 'external' temperature sensor

### ISSUE THREAD

**Issue by ananchev** [smar000/evohome-Listener#14]
This is actually not an issue, but more open request for information and advice. 

I am investigating a way to control my evohome zones based on temperature measurement by external sensor e.g. an xiaomi mi (read via zigbee).  Reason being that the sensors built into my HR92 radiator valves report T locally and even with the OOTB correction possibilities cannot provide reliable, compared to the real zone temp, reading. 

I am considering to position the external sensor where I want it and for set target temperatures for the zone, perform number of measurements of the actual temperature via the xiaomi mi - e.g. every hour of a day.  This way will know the corrections to apply as setting for evohome (via openhab) for obtaining given room temperature. Seems the scenario should be possible via the evohome-Listener. 

A possible alternative would be to directly control the HR92 valve position instead of its temp measurements (using similar approach to build correlation curves). Is this something that can be done via the script?

BTW, all comments or other ideas would be very welcome :)

**Comment by smar000** [comment]
Have a look at the closed issues, as I think another user was trying to do something similar.  In theory using your xiomi and emulating a thermostat on the evohome radio network should be possible, but I suspect not with the script as it stands (it does not support binding for example, which you would need to do, to let the evohome controller know that it is the thermostat device for a zone etc).

I don't believe directly controlling the valve positions of HR92s via radio messages are possible.

**Comment by ananchev** [comment]
I will have a look, thanks! 
Actually, I have not considered the idea to directly emulate the thermostat (i.e.  the T87RF device), but to define in OpenHab the logic on what measured by xiaomi T, what T to be set to the HR92 via the script. I have some doubts how 'stable' the dependency between both will will be, but I expect it should work.
