### ISSUE TITLE
Feature request: auto reconnect to MQTT server

### ISSUE THREAD

**Issue by dystechnic** [smar000/evohome-Listener#17]
Hi,
While doing some maintenance on my MQTT server I noticed that when the script looses connection to the MQTT server it does not reconnect automatically.
I had to bring the MQTT server down for a short while (reboot) so the connection was lost. The only way to reconnect is manually stop and restart the script.

Is it possible to implement a function so that it will reconnect on a connection-los and tries this forever or for a defined period?

Thanx and regards,

Ed.

**Comment by number42net** [comment]
I've submitted pull request #19 which addresses this issue. Currently the script already re-connects automatically, but only subscribes once during initialisation and not on re-connect.

In the mean time you can clone my fork as well to confirm the fix.

**Comment by dystechnic** [comment]
Thanx. 
I will test your fork after this weekend.

**Comment by number42net** [comment]
@dystechnic It might be better to wait a bit, I think my commit also has a different key in devices.json (zone_id instead of zoneId).

**Comment by smar000** [comment]
Thanks @number42net for all your help on this and the zoneId matter. Your changes have been merged a short while ago, and so good to go.
