### ISSUE TITLE
zone_id or zoneID?

### ISSUE THREAD

**Issue by lloyda** [smar000/evohome-Listener#20]
devices_new,json seems to mix the use of zone_id and zoneId.  Don't know if there is a valid reason for this, but caused a bit of head scratching when trying to create be devices.json by copy/paste.

`{
    "01:111111": {
        "name": "Living Room",
        "zoneId": 1,
        "zoneMaster": true
    },
    "01:185426": {
        "name": "01:185426",
        "zoneMaster": false,
        "zone_id": -1
    },
    "04:003222": {
        "name": "04:003222",
        "zoneMaster": false,
        "zone_id": -1
    },
    "04:003224": {
        "name": "Study",
        "zoneId": 2,
        "zoneMaster": true
    },
    "04:003288": {
        "name": "04:003288",
        "zoneMaster": false,
        "zone_id": -1
    },
    "12:089598": {
        "name": "12:089598",
        "zoneMaster": false,
        "zone_id": -1
    },
    "13:197705": {
        "name": "13:197705",
        "zoneMaster": false,
        "zone_id": -1
    },
    "18:056026": {
        "name": "EvoGateway",
        "zoneId": 240,
        "zoneMaster": true
 `

**Comment by smar000** [comment]
Sorry, that was a bug that crept in some months back when refactoring. Correct format is to use "zoneId" as in the `devices.json` sample file. The `devices_new.json` was incorrectly showing "zone_id" .

Updated version just uploaded which should fix this.
