### ISSUE TITLE
Nano Pinout

### ISSUE THREAD

**Issue by daan04** [smar000/evohome-Listener#25]
Hi,

I am trying to build your project, but I am having problems connecting the cc1101 to the Arduino Nano.

Could you please clarify the pins used? For instance in your example you reference pin 32. I assume you mean pin 23 (D18)?

Thanks in advance!

**Comment by smar000** [comment]
The pin numbers may depend on your specific nano or nano clone. The pin 32 refers to the numbers in the grey boxes on this diagram: http://christianto.tjahyadi.com/wp-content/uploads/2014/11/nano.jpg

More importantly, you need to just match the function of the pin on the cc1101 to the corresponding one on the nano. The above pin 32 is the interrupt 0, which corresponds to the GD2 pin on the radio.

**Comment by daan04** [comment]
Thanks for your fast reply, and all the best for 2021!

I’ve seen a lot of Nano-pinout-pictures already, but not this one :)

Best regards,

Daniel

**Comment by smar000** [comment]
Thanks and all the best to you too!

Hope you got it working. Don't hesitate to reach out if you have any further difficulties.
