### ISSUE TITLE
DT92E not supported

### ISSUE THREAD

**Issue by lloyda** [smar000/evohome-Listener#30]
I have a DT92E thermostat, and it is not currently supported.  Adding

 `DEVICE_TYPE["12"] = "STAT" # DT92E `

seems to give me at least basic functionality, but I never see battery status.  I don't know if this is because it is not transmitted, or because it is not decoded correctly.

**Comment by smar000** [comment]
Sorry, I can't really help with that one as I don't have the DT92E myself. If it uses the same protocol as the other devices (which I assume it would), then battery responses would be decoded if they came through. You can try looking through the logs to see if there are any uknown messages coming from that device.
