### ISSUE TITLE
Monitor multiple EvoHome systems

### ISSUE THREAD

**Issue by petermdevries** [smar000/evohome-Listener#38]
I have 2 seperate EvoHome systems in my house. 
Would it be possible to monitor them both with a single evoGateway?

Just started monitoring but it looks like once it found a controller, it builds up only a list of devices/zones related to that specific controller. Alternative would be to run 2 evoGateway scripts in parallel, but I'm afraid that will require 2 hardware devices (2 separate COM ports)?

**Comment by smar000** [comment]
evoGateway uses the `ramses_rf` library for all the underlying communications related functionalty. I don't believe that ramses_rf supports multiple controllers at this time, but best would be check with the author of the library.

Running two instances of evoGateway will require two hardware devices/com ports etc. Although this is not supported by the ramses_rf library (it warns about having two such hardware devices on the same network), I have used it in this way whilst developing, and it seemed to work for the most part.

**Comment by petermdevries** [comment]
Ok, thanks... I just ordered an additional hardware device. :)
