### ISSUE TITLE
Packet.log getting big

### ISSUE THREAD

**Issue by Maikel-K** [smar000/evohome-Listener#43]
Hi,

I have the gateway running for a while now and the packet.log file is already 40mb big.
Isnt it possible to get a folder for example with the log files and write a new log every midnight for example?

**Comment by smar000** [comment]
There should be some log rotating in the code. Unfortunatley I don't have the time at the moment to see what is going on, but will come back to it as and when time permits.

**Comment by Maikel-K** [comment]
No problem!

**Comment by smar000** [comment]
Packet log rotation should now be working. You can add the following into either the evoGateway config file or the ramses schema file (under the config section, and in lower case as per the rest of the schema):

```
LOG_FILE_ROTATE_COUNT       = 9
LOG_FILE_ROTATE_BYTES       = 1000000

```
