### ISSUE TITLE
Wrong version of ramses_rf by defaut requiments

### ISSUE THREAD

**Issue by davevleugel** [smar000/evohome-Listener#44]
Hello,

I did an fresh rpi3b install with raspbian. I did install python 3.9.2 on the side. 

I get the next output at requirements.txt:
`pi@raspberrypi:~/Downloads/evoGateway_11022022 $ pip install -r requirements.txt
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: colorama==0.4.3 in /home/pi/.local/lib/python3.9/site-packages (from -r requirements.txt (line 1)) (0.4.3)
Requirement already satisfied: ramses_rf==0.18.6 in /home/pi/.local/lib/python3.9/site-packages (from -r requirements.txt (line 2)) (0.18.6)
Requirement already satisfied: paho_mqtt==1.6.1 in /home/pi/.local/lib/python3.9/site-packages (from -r requirements.txt (line 3)) (1.6.1)
Requirement already satisfied: pyserial-asyncio>=0.5 in /home/pi/.local/lib/python3.9/site-packages (from ramses_rf==0.18.6->-r requirements.txt (line 2)) (0.6)
Requirement already satisfied: voluptuous>=0.12.2 in /home/pi/.local/lib/python3.9/site-packages (from ramses_rf==0.18.6->-r requirements.txt (line 2)) (0.12.2)
Requirement already satisfied: colorlog>=6.5.0 in /home/pi/.local/lib/python3.9/site-packages (from ramses_rf==0.18.6->-r requirements.txt (line 2)) (6.6.0)
Requirement already satisfied: pyserial in /usr/lib/python3/dist-packages (from pyserial-asyncio>=0.5->ramses_rf==0.18.6->-r requirements.txt (line 2)) (3.5b0)
`

If i use ramses_rf standalone it works:

`
pi@raspberrypi:~/Downloads/ramses_rf $ python3 -O client.py -rr listen /dev/serial/by-id/usb-SparkFun_evofw3_atmega32u4-if00

client.py: Starting ramses_rf...
12:13:32.066 It is strongly recommended to provide a known_list, and use it as a whitelist (device_id filter), configure: enforce_known_list = True
12:13:32.078 Not using any device filter: using a known_list (as a whitelist) is strongly recommended)
12:15:26.507 || TRV:032773 | CTL:124961 |  I | window_state     |  00  || {'zone_idx': '00', 'window_open': Fal
12:16:16.291 || CTL:124961 |            |  I | system_sync      |      || {'remaining_seconds': 198.0, '_next_s
12:16:16.326 || CTL:124961 |            |  I | zone_params      | [..] || [{'zone_idx': '00', 'min_temp': 16.0,
12:17:07.743 || TRV:032767 |            |  I | temperature      |      || {'temperature': 14.71}
12:17:11.950 || TRV:032769 | CTL:124961 |  I | heat_demand      |  04  || {'zone_idx': '04', 'heat_demand': 0.1
12:17:27.834 || STA:136631 |            |  I | temperature      |      || {'temperature': 16.13}
`

But running the evogateway:
`
pi@raspberrypi:~/Downloads/evoGateway_11022022 $ python evogateway.py
2022-02-11 12:35:36,896 [1090] The schema file 'ramses_rf_schema.json' was not found'
2022-02-11 12:35:36,898 [1103] Schema file missing or the 'known_list' section is missing. Defaulting to ramses_rf 'eavesdropping' mode
2022-02-11 12:35:36 | Existing devices file not found. Defaulting to 'eavesdropping' mode
2022-02-11 12:35:36 | # evogateway 3.7-0.18.6 (using 'ramses_rf' library 0.18.6)
enable_eavesdrop enabled: this is discouraged for routine use (there be dragons here)
It is strongly recommended to provide a known_list, and use it as a whitelist (device_id filter), configure: enforce_known_list = True
Traceback (most recent call last):
  File "/home/pi/Downloads/evoGateway_11022022/evogateway.py", line 1193, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/pi/Downloads/evoGateway_11022022/evogateway.py", line 1168, in main
    update_zones_from_gwy()
  File "/home/pi/Downloads/evoGateway_11022022/evogateway.py", line 653, in update_zones_from_gwy
    schema = GWY.evo.schema or GWY.schema if GWY else {}
AttributeError: 'NoneType' object has no attribute 'schema'
`

I think it is the wrong ramses_rf version, i see some changes in the code about the version. 

My default python is the 3.9.2:

`
pi@raspberrypi:~/Downloads/evoGateway_11022022 $ pip -V
pip 20.3.4 from /usr/lib/python3/dist-packages/pip (python 3.9)
pi@raspberrypi:~/Downloads/evoGateway_11022022 $ python --version
Python 3.9.2
pi@raspberrypi:~/Downloads/evoGateway_11022022 $
`

**Comment by davevleugel** [comment]
`
pi@raspberrypi:~/Downloads/evoGateway_11022022 $ pip -V
pip 20.3.4 from /usr/lib/python3/dist-packages/pip (python 3.9)
pi@raspberrypi:~/Downloads/evoGateway_11022022 $ python --version
Python 3.9.2
pi@raspberrypi:~/Downloads/evoGateway_11022022 $
`

**Comment by davevleugel** [comment]
I did try `pip install git+https://github.com/zxdavb/ramses_rf.git@0.18.6`, installation succesfull but stil same output

**Comment by smar000** [comment]
Issue was not with ramses version, but with a last minute change I had added in initalising zones data. Just uploaded a bug fix.

**Comment by davevleugel** [comment]
thanks! i did mislook to the actual problem -_-thanks mate!
