### ISSUE TITLE
Question: how to use get schedule

### ISSUE THREAD

**Issue by attila-kun00** [smar000/evohome-Listener#46]
Hello,

I'm tring to get schedule with the following payload:
`{"command": "get_schedule", "ctl_id": "01:183483", "zone_idx": "00"}`

but I get the following error:
`2022-04-16T08:30:57.951883646Z 2022-04-16 08:30:57,950 [348] get_schedule_async(): Error: 'NoneType' object has no attribute 'get_schedule'`

Other commands work fine.
Can you please help me what is the correct way to get/set the evohome's schedule?

I'm using the code from the master branch, which uses ramses_rf version 0.18.6.

**Comment by smar000** [comment]
Hi

Sorry for the late reply. The schedules part is not fully tested, both on my side and the last time I checked, on the ramses_rf side - e.g. https://github.com/zxdavb/ramses_rf/issues/38#issuecomment-941430545.

I'll have another look next time I do an update of my ramses_rf library, but that probably won't be for a few weeks at the earliest.

**Comment by smar000** [comment]
Hi @attila-kun00 

Sorry it took so long, but you can try getting and setting schedules with the latest build. Note that command syntax has slightly changed, e.g.:

`{"command": "set_schedule", "zone_idx": "02", "schedule": [{"day_of_week": 0, "switchpoints": [{"time_of_day": "07:20", "heat_setpoint": 22.0}, {"time_of_day": "07:50", "heat_setpoint": 15.0}, {"time_of_day": "19:30", "heat_setpoint": 21.0}, {"time_of_day": "21:50", "heat_setpoint": 5.0}]}] }
`
