### ISSUE TITLE
Binding TRVs

### ISSUE THREAD

**Issue by serych** [smar000/evohome-Listener#49]
Hi,
I have functional evoGateway which is receiving messages from four TRVs (without evohome controller). Is there any way, how to bind TRVs to the evoGateway? Or is it done just by defining zones in devices.json? Any example configuration or tutorial? 

Thanks a lot for any info!

Jakub

**Comment by smar000** [comment]
Hi

Binding with the evoGateway is not supported, as evoGateway's role is just to provide a gateway via MQTT - i.e. it has no control functionality in itself for controlling your heating system.

However, you may want to look at the underlying `ramses_rf` library that evoGateway uses, in case there is anything there that can help you with this.
