### ISSUE TITLE
add from_id to "code" message

### ISSUE THREAD

**Issue by chris-hunter** [smar000/evohome-Listener#57]
I wonder if you would consider adding the following lines to evogateway.py on the next update:
(line 978, in the mqtt_process_msg function)
                if "from_id" in json_data:
                    from_id = json_data["from_id"]
                    gw_cmd = GWY.create_cmd(verb, dest_id, command_code, payload, from_id=from_id)
                else:
                    gw_cmd = GWY.create_cmd(verb, dest_id, command_code, payload)                 # Command.from_attrs()
This allows the impersonation of a different device to send a message from, and is supported in zxdzvb's ramses_rf library.
I am using this as my controller sometimes drops reception to one of the sensors, and when this happens I'm using my evoGateway as a repeater.
Thank you again for the excellent program.

**Comment by smar000** [comment]
Hi

Sure! I'm not sure when the next update will be, but happy to add the above at that time. Alternatively, feel free to issue a pull request.

**Comment by chris-hunter** [comment]
Hi,
I've tried to issue a pull request (I have never done this before so please let me know if it hasn't worked).
