### ISSUE TITLE
How to request all components to send their ID

### ISSUE THREAD

**Issue by Maikel-K** [smar000/evohome-Listener#7]
Hi,

Got a new nano and it seems to be working now, but is there a command to issue to request all the components in the system to send there ID's?

And how do we issue it?

Thanks,

Maikel

**Comment by smar000** [comment]
Good to hear that your new nano is working.

I am not aware of any specific command to request all components to send their ID (I don't think there is any such command for 'normal' devices - possibly something that a 'controller' can do?). Normally I just leave the system running for a few hours, in which time all devices should have sent multiple messages to the controller. Their IDs will then be picked up by the script assuming your nano is 'hearing' the messages. 

You should note though that with these nano setups, I don't believe 100% of messages get through. I have two such nanos operating concurrently, and do occasionally see messages received by one unit that are not showing in the other. Infrequent, but it does happen.

**Comment by Maikel-K** [comment]
Okay thanks, I am still missing one HR92 valve although I’m issuing commands via the controller and the app.

Is there a way to retrieve the ID from the HR92? Via serialnumber or a menu option or something like that?

It could also because of the position of the nano compared to the HR92.

I have another CC1101 with SMA connector but the supplied antenne says 433 MHz on it. I ordered a 868 one but it still has to arrive.

Is it possible to use the TX/RX pins on the nano to connect it to a ESP8266 and use ESPEasy as a ser2net unit to place the Evohome reciever where we want?

**Comment by smar000** [comment]
> Is there a way to retrieve the ID from the HR92? Via serialnumber or a menu option or something like that?

Try pressing the button on the HR92. This normally triggers the sending of a message over the radio to the controller, which the gateway script should pick up (assuming it is able to 'hear' the HR92 - maybe relocate the listener or temporarily take the HR92 off the radiator and bring it closer?).

> Is it possible to use the TX/RX pins on the nano to connect it to a ESP8266 and use ESPEasy as a ser2net unit to place the Evohome reciever where we want?

No idea! Theoretically possible I should think. Easier to just use an RPi...

**Comment by Maikel-K** [comment]
Thanks, i will await the new antenna to test the other module i have laying around

Will try and connect the ESP8266 to the Nano and see what is possible.

**Comment by smar000** [comment]
Ok and good luck! Do let me know if you get the ESP working.
