### ISSUE TITLE
Error during install (?)...

### ISSUE THREAD

**Issue by darekhome** [smar000/evohome-Listener#9]
I have following message.
Is that something wrong?

`root@Debian10:~/evohome-Listener# python evogateway.py install
Traceback (most recent call last):
  File "evogateway.py", line 52, in <module>
    from enum import Enum, IntEnum
ImportError: No module named enum`

**Comment by smar000** [comment]
Hi 

There is no need to install the script. Assuming you have the other requireqments already installed (e.g. paho-mqtt, pyserial etc), then you just run the script with:

`python evogateway.py`

**Comment by darekhome** [comment]
O.K. Clear... Hover still something not O.K.?
No module 'enum'?

`root@Debian10:~/evohome-Listener# python evogateway.py
Traceback (most recent call last):
  File "evogateway.py", line 52, in <module>
    from enum import Enum, IntEnum
ImportError: No module named enum
root@Debian10:~/evohome-Listener# ls
README.md            devices.json    evogateway.png  evogateway.service
arduino-cc1101.jpeg  evogateway.cfg  evogateway.py   multitail.conf
root@Debian10:~/evohome-Listener#`

**Comment by smar000** [comment]
You don't have the `enum` module installed in your python installation. Actually I don't think the module is still being used by the code, so you can also try commenting out the `import` line.

**Comment by smar000** [comment]
If everything is working ok, I will now close this issue. Feel free to reopen if you are still having issues.
